# Generated by Django 5.2.4 on 2025-07-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Ortobom, Castor, Emma', max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Um breve histórico ou foco da marca.')),
            ],
        ),
        migrations.CreateModel(
            name='MattressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Molas Ensacadas, Espuma D33, Híbrido, Látex', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Explicação sobre o que é este tipo de tecnologia.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='O nome completo do produto. Ex: Colchão Queen Molas Ensacadas Freedom', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Marque para que este produto apareça no site.')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (gerado automaticamente se deixado em branco).', max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Título para o Google (opcional). Se vazio, um padrão será usado.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para o Google (opcional).', max_length=160)),
                ('affiliate_links', models.JSONField(blank=True, help_text='Ex: [{"store": "Amazon", "url": "...", "price": 2499.90}]', null=True)),
                ('image_url', models.URLField(help_text='Link da imagem principal do produto.', max_length=1024)),
                ('page_title', models.CharField(help_text='Título principal que aparecerá no topo da página. Ex: Análise Completa do Colchão Ortobom Freedom', max_length=255)),
                ('introduction_text', models.TextField(help_text='Parágrafo inicial. Apresente o colchão e para quem ele é indicado.')),
                ('comfort_section_title', models.CharField(default='Nível de Conforto e Firmeza', max_length=255)),
                ('comfort_section_text', models.TextField(help_text='Descreva a sensação de deitar no colchão. É macio, firme, intermediário?')),
                ('technology_section_title', models.CharField(default='Tecnologia e Materiais de Construção', max_length=255)),
                ('technology_section_text', models.TextField(help_text='Explique as tecnologias (molas, espumas especiais, tecidos) e como elas beneficiam o usuário.')),
                ('who_is_it_for_section_title', models.CharField(default='Este Colchão é Ideal Para Você?', max_length=255)),
                ('who_is_it_for_text', models.TextField(help_text="Seja específico. Ex: 'Ideal para casais, pessoas que se mexem muito à noite, ou quem sofre com calor.'")),
                ('conclusion_section_title', models.CharField(default='Veredito Final: Vale a Pena Comprar?', max_length=255)),
                ('conclusion_text', models.TextField(help_text='Resuma os pontos e dê sua recomendação final, guiando para o botão de compra.')),
                ('technical_specs', models.JSONField(blank=True, help_text='Use formato JSON. Ex: {"altura_cm": 28, "suporte_peso_kg": 120, "garantia_anos": 5}', null=True)),
                ('pros_and_cons', models.JSONField(blank=True, help_text='Use formato JSON. Ex: {"pros": ["Excelente suporte", "Não esquenta"], "cons": ["Pode ser pesado", "Preço elevado"]}', null=True)),
                ('size', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('QUEEN', 'Queen'), ('KING', 'King')], default='CASAL', max_length=10)),
                ('firmness_level', models.IntegerField(choices=[(1, 'Extra Macio'), (2, 'Macio'), (3, 'Intermediário'), (4, 'Firme'), (5, 'Extra Firme')], default=3)),
                ('target_audience_text', models.CharField(blank=True, help_text="Complete a frase 'Este colchão é perfeito para...'. Ex: 'casais que valorizam a independência de movimentos.'", max_length=255)),
                ('best_for_scenario', models.CharField(blank=True, help_text="Cenário ideal de uso. Ex: 'quartos de hóspedes de luxo', 'aliviar dores na lombar'.", max_length=255)),
                ('user_rating_score', models.DecimalField(blank=True, decimal_places=1, help_text='Nota média de usuários (de 0.0 a 5.0).', max_digits=3, null=True)),
                ('expert_review_snippet', models.TextField(blank=True, help_text="Citação curta de um 'especialista' (você!) que resuma o produto. Ex: 'O melhor equilíbrio entre maciez e suporte que testamos.'")),
                ('awards', models.CharField(blank=True, help_text="Prêmios que o produto ganhou. Ex: 'Selo de Melhor Custo-Benefício 2024'.", max_length=255)),
                ('video_review_url', models.URLField(blank=True, help_text='Link de um vídeo review do YouTube (pode ser seu ou de terceiros).')),
                ('gallery_images', models.JSONField(blank=True, help_text='Links para imagens adicionais. Ex: [{"url": "link1", "alt": "vista de cima"}, {"url": "link2", "alt": "detalhe do tecido"}]', null=True)),
                ('faq_section', models.JSONField(blank=True, help_text='Perguntas e respostas sobre o produto. Ex: [{"question": "Ele vem enrolado?", "answer": "Sim, este modelo é do tipo bed-in-a-box."}]', null=True)),
                ('heat_dissipation_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Nota de 1 a 5 para a capacidade de não esquentar.', null=True)),
                ('motion_isolation_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Nota de 1 a 5 para o isolamento de movimento (bom para casais).', null=True)),
                ('edge_support_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Nota de 1 a 5 para o suporte nas bordas.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=10)),
                ('version', models.IntegerField(default=1, help_text='Versão do conteúdo, para controle interno.')),
                ('last_updated_by_user', models.DateTimeField(auto_now=True, help_text='Data da última atualização do conteúdo.')),
                ('brand', models.ForeignKey(help_text='A marca deste colchão.', on_delete=django.db.models.deletion.PROTECT, to='colchoes.brand')),
                ('main_competitor', models.ForeignKey(blank=True, help_text='Selecione o principal concorrente direto deste produto para criar links de comparação.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colchoes.product')),
                ('mattress_type', models.ForeignKey(help_text='A tecnologia principal do colchão.', on_delete=django.db.models.deletion.PROTECT, to='colchoes.mattresstype')),
            ],
        ),
    ]
