# Generated by Django 5.2.4 on 2025-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colchoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='affiliate_links',
        ),
        migrations.AddField(
            model_name='product',
            name='affiliate_link1',
            field=models.URLField(blank=True, help_text='Ex: "https://www.amazon.com.br/dp/B08XYZ1234"', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='affiliate_link2',
            field=models.URLField(blank=True, help_text='Ex: "https://www.magazine.com.br/dp/B08XYZ1234"', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='affiliate_link3',
            field=models.URLField(blank=True, help_text='Ex: "https://www.mercadolivre.com.br/dp/B08XYZ1234"', null=True),
        ),
    ]
