# Generated by Django 5.2.4 on 2025-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colchoes', '0002_remove_product_affiliate_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do produto (opcional).', null=True, upload_to='product_images/'),
        ),
    ]
