# Generated by Django 5.2.4 on 2025-07-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colchoes', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para o Google (opcional). Se vazio, um padrão será usado.', max_length=75),
        ),
    ]
