# Generated by Django 5.2.4 on 2025-08-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colchoes', '0004_alter_product_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data em que a comparação foi criada.')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável para a comparação.', max_length=255, unique=True)),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_product2', to='colchoes.product')),
                ('produtct1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_product1', to='colchoes.product')),
            ],
        ),
    ]
