# Generated by Django 5.2.4 on 2025-08-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colchoes', '0005_comparison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='produtct1',
            new_name='product1',
        ),
    ]
