# Generated by Django 5.2.4 on 2025-08-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colchoes', '0006_rename_produtct1_comparison_product1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço sugerido do colchão. Ex: 1999.99', max_digits=10, null=True),
        ),
    ]
